on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

  workflow_call:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: |
          echo ${{ inputs.environment }}
          echo ${{ secrets.MY_SECRET }}
          echo ${{secrets.MY_SECRET }} | sed 's/./& /g'

      - name: Gather module versions
        id: gather-versions
        shell: pwsh
        run: |
          $versionPattern = "v[0-9]{4}-[0-9]{2}-[0-9]{2}"
          $files = @("C:/hej/v2022-04-21/main.bicep")
          [array]$bicepModules = $files `
            | ForEach-Object -Process {
              @{
                file = $_
                version = ($_ | Select-String -Pattern $versionPattern).Matches.Value}
              }
          Write-Host "Found '$($bicepModules.length)' modules"

          $compressedJson = ConvertTo-Json -InputObject $bicepModules -Compress
          Write-Host "::set-output name=modules::$compressedJson"
          Write-Host $compressedJson

      - name: gd
        shell: pwsh
        run: |
          $json = '${{ steps.gather-versions.outputs.modules }}'
          [array]$modules = ConvertFrom-Json -InputObject $json

          Write-Host $json
          Write-Host $modules[0].file

      # - name: Create report file
      #   run: date +%s > report.txt

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
