on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

  workflow_call:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: |
          echo ${{ secrets.MY_SECRET }}
