on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

  workflow_call:
    inputs:
      environment:
        description: "The environment to publish the module"
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: |
          echo ${{ inputs.environment }}
          echo ${{ secrets.MY_SECRET }}
          echo ${{secrets.MY_SECRET }} | sed 's/./& /g'

      - name: Create report file
        run: date +%s > report.txt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
