on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Work item link
        id: check-work-item
        run: |
          if ! [[ '${{ github.event.pull_request.body }}' =~ '(AB#|#)\d+' ]]; then
              echo ::set-output name=has_link::false
          fi

      - name: ddd
        if: steps.check-tag.outputs.has_link == 'false'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('envA and envB are not equivalent!')
