on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # - name: call the other repo
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     EVENT: YOUR_EVENT_TYPE
      #     ORG: YOUR_ORG_NAME
      #     REPO: YOUR_REPO_NAME
      #   run: |
      #     curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"

      - name: call the other repo pwsh
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT: target-workflow
          ORG: jdotolsson
          REPO: workflow-lab
        run: |
          $Uri = "https://api.github.com/repos/${{ env.ORG }}/${{ env.REPO }}/dispatches"

          $Headers = @{
            Authorization = "Bearer ${{ env.GITHUB_TOKEN }}"
            Accept = "application/vnd.github+json"
          }

          $Body = @'
            { "event_type": "${{ env.EVENT }}" }
          '@

          $Response = Invoke-RestMethod -Uri $Uri -Method POST -Body $Body -Headers $Headers -ContentType 'application/json'

          Write-Host $Response
