name: Summary

on:
  push:
    branches: [main]

jobs:
  summaryReport_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get Report
        id: get-report
        shell: pwsh
        run: |
          $report = @"
          # Service Bus consolidation

          [Go to explication to understand these tables](##-Explanation)

          ## Topics

          | Topic Name  | Defined in configuration | Exist in Service bus | Service Bus Name |
          | ----------- | :----------------------: | :------------------: | ---------------- |
          | sbt-random  |    :heavy_check_mark:    |         :x:          | sb-au-nonprod    |
          | sbt-random2 |    :heavy_check_mark:    |         :x:          | sb-au-nonprod    |

          ## Explanation

          Stuff

          "@

          Write-Host $report

          echo "{report}={$report}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Adding markdown
        shell: pwsh
        run: echo '### Hello world! :rocket:' >> $Env:GITHUB_STEP_SUMMARY

      - name: test
        shell: pwsh
        run: ${{ steps.get-report.outputs.report }}

      # - name: Report
      #   shell: pwsh
      #   run: |
      #     echo ${{ steps.get-report.outputs.report }} >> $Env:GITHUB_STEP_SUMMARY
