name: Summary

on:
  push:
    branches: [main]

jobs:
  summaryReport_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get Report
        id: get-report
        shell: pwsh
        run: |
          $report = "
          # Service Bus consolidation

          ## Topics

          | Topic Name  | Defined in configuration | Exist in Service bus | Service Bus Name |
          | ----------- | :----------------------: | :------------------: | ---------------- |
          | sbt-random  |    :heavy_check_mark:    |         :x:          | sb-au-nonprod    |
          | sbt-random2 |    :heavy_check_mark:    |         :x:          | sb-au-nonprod    |

          ## Explanation

          Stuff

          "

          echo "report=$report" >> $Env:GITHUB_OUTPUT

      - name: Adding markdown
        shell: pwsh
        run: echo '### Hello world! :rocket:' >> $Env:GITHUB_STEP_SUMMARY

      - name: test
        shell: pwsh
        run: ${{ steps.get-report.outputs.report }}

      - name: Set color
        shell: pwsh
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $Env:GITHUB_OUTPUT
      - name: Get color
        shell: pwsh
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      # - name: Report
      #   shell: pwsh
      #   run: |
      #     echo ${{ steps.get-report.outputs.report }} >> $Env:GITHUB_STEP_SUMMARY
